/**
 * Genuine NCR corporate companies dataset (Noida Sector 62, Sector 126, Sector 132, Gurgaon)
 * Features actual companies with physical campuses in Noida Sector 62 and authentic career URLs.
 */

const now = new Date();
const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
const tomorrow = new Date(today.getTime() + 24 * 60 * 60 * 1000);

const MOCK_JOBS_DATA = [
  // 1. Tata Consultancy Services (TCS) - Sector 62, Noida (~0.4 km)
  {
    _id: '670000000000000000000001',
    title: 'Frontend React Developer',
    companyName: 'Tata Consultancy Services (TCS)',
    companyLogo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=100&auto=format&fit=crop&q=80',
    description: 'TCS Noida is hiring React Developers for its Global Banking & Financial Services digital transformation unit. You will engineer modular web applications using React, Redux Toolkit, and Tailwind CSS.',
    responsibilities: [
      'Develop modular and accessible UI components with React and modern JavaScript',
      'Integrate core REST APIs and manage client-side caching',
      'Ensure high performance across mobile and desktop web browsers',
    ],
    requirements: [
      'Strong proficiency in React, JavaScript (ES6+), HTML5, and CSS3',
      'Understanding of component lifecycle, hooks, and state management',
      'B.Tech / BCA / MCA / B.Sc or relevant software engineering background',
    ],
    skills: ['React', 'JavaScript', 'HTML5', 'Tailwind CSS', 'Git', 'TypeScript', 'Redux'],
    category: 'Technology / IT',
    categories: ['Technology / IT'],
    subCategory: 'Frontend Development',
    salaryMin: 500000,
    salaryMax: 950000,
    experienceLevel: 'Fresher',
    experienceMin: 0,
    experienceMax: 2,
    employmentType: 'Full Time',
    workMode: 'Hybrid',
    locationName: 'Plot 22 & 23, Sector 62, Noida',
    city: 'Noida',
    state: 'Uttar Pradesh',
    location: { type: 'Point', coordinates: [77.3615, 28.6275] }, // Exactly Sector 62 (~0.4 km away)
    postedAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
    walkIn: false,
    applyUrl: 'https://www.tcs.com/careers',
    verified: true,
    status: 'active',
  },

  // 2. Tech Mahindra - Sector 62, Noida (~0.6 km)
  {
    _id: '670000000000000000000002',
    title: 'Software Engineer - Full Stack (Node.js & React)',
    companyName: 'Tech Mahindra',
    companyLogo: 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=100&auto=format&fit=crop&q=80',
    description: 'Tech Mahindra Noida Development Center is looking for Full Stack Developers to architect high-throughput web systems utilizing Node.js, Express, MongoDB, and React.',
    responsibilities: [
      'Design RESTful microservices and backend data pipelines in Node.js and Express',
      'Build rich, responsive interfaces using React and modern CSS',
      'Optimize MongoDB queries and maintain high API availability',
    ],
    requirements: [
      'Hands-on experience with Node.js, Express.js, MongoDB, and React',
      'Strong grasp of async programming, REST architecture, and database indexing',
      'Knowledge of JWT authentication and API security standards',
    ],
    skills: ['React', 'Node.js', 'Express.js', 'MongoDB', 'JavaScript', 'REST API'],
    category: 'Technology / IT',
    categories: ['Technology / IT'],
    subCategory: 'Full Stack Development',
    salaryMin: 600000,
    salaryMax: 1200000,
    experienceLevel: '1-3 years',
    experienceMin: 1,
    experienceMax: 3,
    employmentType: 'Full Time',
    workMode: 'On-site',
    locationName: 'A-7, Sector 62, Noida',
    city: 'Noida',
    state: 'Uttar Pradesh',
    location: { type: 'Point', coordinates: [77.3635, 28.6295] }, // Exactly Sector 62 (~0.6 km away)
    postedAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    walkIn: false,
    applyUrl: 'https://careers.techmahindra.com',
    verified: true,
    status: 'active',
  },

  // 3. MEGA WALK-IN: Tech Mahindra / TCS Sector 62 - HAPPENING TODAY
  {
    _id: '670000000000000000000003',
    title: 'MEGA WALK-IN DRIVE: Software Engineers & Web Developers',
    companyName: 'Tech Mahindra',
    companyLogo: 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=100&auto=format&fit=crop&q=80',
    description: 'Direct in-person hiring drive at Tech Mahindra Sector 62 campus. Spot technical assessments and face-to-face evaluations for Web Developers and Software Engineers. On-the-spot offer letters for qualifying candidates.',
    responsibilities: [
      'Participate in in-person technical evaluation and live coding problem solving',
      'Technical interview with Senior Delivery Leads on MERN / Full Stack concepts',
      'Immediate document verification and offer rolling upon selection',
    ],
    requirements: [
      'Proficiency in React, JavaScript, Node.js, or Java',
      'Degree in B.Tech / BE / BCA / MCA / B.Sc (Computer Science / IT)',
      'Carry 2 copies of updated CV, photo ID (Aadhar/PAN), and college transcripts',
    ],
    skills: ['React', 'Node.js', 'JavaScript', 'MongoDB', 'Java'],
    category: 'Technology / IT',
    categories: ['Technology / IT'],
    subCategory: 'Full Stack Development',
    salaryMin: 450000,
    salaryMax: 900000,
    experienceLevel: 'Fresher',
    experienceMin: 0,
    experienceMax: 2,
    employmentType: 'Walk-in',
    workMode: 'On-site',
    locationName: 'Tech Mahindra Campus, A-7, Sector 62, Noida',
    city: 'Noida',
    state: 'Uttar Pradesh',
    location: { type: 'Point', coordinates: [77.3635, 28.6295] },
    postedAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    walkIn: true,
    walkInDate: today,
    walkInStartTime: '10:00 AM',
    walkInEndTime: '04:30 PM',
    venue: 'Tech Mahindra Campus, Auditorium Block, A-7, Sector 62, Noida (Near Electronic City Metro Station)',
    requiredDocuments: ['2 Copies of Resume', 'Original Govt ID Proof (Aadhar/PAN)', 'Educational Certificates'],
    contactPhone: '+91 120 4567890',
    contactEmail: 'walkin.noida@techmahindra.com',
    applyUrl: 'https://careers.techmahindra.com',
    verified: true,
    status: 'active',
  },

  // 4. Samsung R&D Institute India - Logix Cyber Park, Sector 62 (~0.8 km)
  {
    _id: '670000000000000000000004',
    title: 'AI & Mobile Software Engineer',
    companyName: 'Samsung R&D Institute India',
    companyLogo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=100&auto=format&fit=crop&q=80',
    description: 'Join Samsung R&D Noida engineering next-generation consumer intelligence and mobile cloud microservices. Work on on-device machine learning, GenAI pipelines, and scalable APIs.',
    responsibilities: [
      'Design on-device and cloud AI microservices',
      'Optimize algorithmic latency for multi-million user mobile ecosystems',
      'Collaborate with global engineering teams across Korea and Bangalore',
    ],
    requirements: [
      'Solid foundations in Data Structures, Algorithms, Python or C++ or Java',
      'Exposure to Machine Learning / Deep Learning or Android development',
      'Strong problem-solving capability',
    ],
    skills: ['Python', 'Machine Learning', 'Java', 'Generative AI', 'C++', 'Git'],
    category: 'Technology / IT',
    categories: ['Technology / IT'],
    subCategory: 'Data Science & AI',
    salaryMin: 900000,
    salaryMax: 1800000,
    experienceLevel: 'Fresher',
    experienceMin: 0,
    experienceMax: 3,
    employmentType: 'Full Time',
    workMode: 'On-site',
    locationName: 'Logix Cyber Park, Tower D, Sector 62, Noida',
    city: 'Noida',
    state: 'Uttar Pradesh',
    location: { type: 'Point', coordinates: [77.3685, 28.6260] }, // Sector 62 (~0.8 km away)
    postedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    walkIn: false,
    applyUrl: 'https://research.samsung.com',
    verified: true,
    status: 'active',
  },

  // 5. Pine Labs - Sector 62, Noida (~0.3 km)
  {
    _id: '670000000000000000000005',
    title: 'Business Development Executive (Merchant Fintech Sales)',
    companyName: 'Pine Labs',
    companyLogo: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=100&auto=format&fit=crop&q=80',
    description: 'Pine Labs is expanding its merchant commerce & POS solutions across North India. Looking for driven Business Development Executives to onboard enterprise retail merchants and partners.',
    responsibilities: [
      'Acquire and onboard corporate retail and enterprise merchant accounts',
      'Demonstrate Pine Labs payment gateway and PoS terminals',
      'Manage pipeline forecasting and client relationship growth',
    ],
    requirements: [
      'Enthusiasm for fintech and merchant commerce solutions',
      'Strong interpersonal, communication, and negotiation abilities',
      'Target-oriented mindset with high customer empathy',
    ],
    skills: ['Business Development', 'Inside Sales', 'Lead Generation', 'Client Relations', 'Negotiation Skills'],
    category: 'Sales',
    categories: ['Sales'],
    subCategory: 'Business Development (BDE)',
    salaryMin: 400000,
    salaryMax: 750000,
    experienceLevel: 'Fresher',
    experienceMin: 0,
    experienceMax: 2,
    employmentType: 'Full Time',
    workMode: 'On-site',
    locationName: 'Plot 22, Sector 62, Noida',
    city: 'Noida',
    state: 'Uttar Pradesh',
    location: { type: 'Point', coordinates: [77.3615, 28.6285] }, // Sector 62 (~0.3 km away)
    postedAt: new Date(Date.now() - 7 * 60 * 60 * 1000),
    walkIn: false,
    applyUrl: 'https://www.pinelabs.com/careers',
    verified: true,
    status: 'active',
  },

  // 6. WALK-IN DRIVE: Field Sales & Operations - TOMORROW (Noida Sector 62)
  {
    _id: '670000000000000000000006',
    title: 'WALK-IN INTERVIEWS: Field Sales Executives & Customer Associates',
    companyName: 'Pine Labs',
    companyLogo: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=100&auto=format&fit=crop&q=80',
    description: 'Walk-in recruitment drive for Field Sales Executives and Customer Success associates in Noida & East Delhi. Immediate same-day hiring with attractive performance incentives and travel allowances.',
    responsibilities: [
      'Direct merchant visits in commercial markets',
      'Product demonstration and immediate merchant onboarding',
    ],
    requirements: [
      '12th Pass or Graduate candidates eligible',
      'Two-wheeler and valid driving license preferred for field positions',
    ],
    skills: ['Field Sales', 'Telecalling', 'Customer Relations'],
    category: 'Sales',
    categories: ['Sales', 'Operations'],
    subCategory: 'Field Sales',
    salaryMin: 300000,
    salaryMax: 550000,
    experienceLevel: 'Fresher',
    experienceMin: 0,
    experienceMax: 2,
    employmentType: 'Walk-in',
    workMode: 'On-site',
    locationName: 'Pine Labs Towers, Plot 22, Sector 62, Noida',
    city: 'Noida',
    state: 'Uttar Pradesh',
    location: { type: 'Point', coordinates: [77.3615, 28.6285] },
    postedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    walkIn: true,
    walkInDate: tomorrow,
    walkInStartTime: '10:30 AM',
    walkInEndTime: '04:00 PM',
    venue: 'Pine Labs Campus, Ground Floor Recruitment Bay, Plot 22, Sector 62, Noida',
    requiredDocuments: ['Updated Resume', 'Aadhar Card / Driving License'],
    contactPhone: '+91 120 4099880',
    applyUrl: 'https://www.pinelabs.com/careers',
    verified: true,
    status: 'active',
  },

  // 7. HCL Technologies - Technology Hub, Sector 126, Noida (~9.5 km)
  {
    _id: '670000000000000000000007',
    title: 'Cloud & DevOps Engineer (AWS / Docker)',
    companyName: 'HCL Technologies',
    companyLogo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=100&auto=format&fit=crop&q=80',
    description: 'HCL Noida Technology Hub is hiring Cloud Engineers to automate multi-region AWS cloud deployments, monitor containerized microservices, and build CI/CD pipelines.',
    responsibilities: [
      'Manage AWS cloud infrastructure using Terraform and CloudFormation',
      'Maintain Docker containers and Kubernetes deployments',
      'Automate release management using GitHub Actions and Jenkins',
    ],
    requirements: [
      'Knowledge of AWS services (EC2, S3, IAM, VPC, CloudWatch)',
      'Hands-on experience with Linux CLI, Docker, and shell scripting',
      'Familiarity with CI/CD concepts',
    ],
    skills: ['AWS', 'Docker', 'Kubernetes', 'Linux', 'CI/CD', 'Git'],
    category: 'Technology / IT',
    categories: ['Technology / IT'],
    subCategory: 'DevOps & Cloud',
    salaryMin: 700000,
    salaryMax: 1400000,
    experienceLevel: '1-3 years',
    experienceMin: 1,
    experienceMax: 4,
    employmentType: 'Full Time',
    workMode: 'Hybrid',
    locationName: 'Technology Hub, SEZ, Sector 126, Noida',
    city: 'Noida',
    state: 'Uttar Pradesh',
    location: { type: 'Point', coordinates: [77.3390, 28.5440] }, // Sector 126 (~9.5 km)
    postedAt: new Date(Date.now() - 14 * 60 * 60 * 1000),
    walkIn: false,
    applyUrl: 'https://www.hcltech.com/careers',
    verified: true,
    status: 'active',
  },

  // 8. Info Edge (Naukri.com) - Sector 132, Noida (~13 km)
  {
    _id: '670000000000000000000008',
    title: 'HR Recruiter / Talent Acquisition Specialist',
    companyName: 'Info Edge (Naukri.com)',
    companyLogo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=100&auto=format&fit=crop&q=80',
    description: 'Info Edge (parent company of Naukri.com, Jeevansathi, 99acres) is seeking Talent Acquisition Specialists to lead tech & non-tech candidate sourcing, interview scheduling, and recruitment campaigns.',
    responsibilities: [
      'Source, screen, and engage high-caliber candidates across digital platforms',
      'Coordinate interview panels and optimize candidate conversion funnels',
      'Track recruitment metrics, offer acceptance ratios, and campus relations',
    ],
    requirements: [
      'MBA in HR or Graduate with passion for people management and hiring',
      'Superb communication and relationship-building capabilities',
      'Proficiency in candidate screening and Excel tracking',
    ],
    skills: ['Recruitment', 'Talent Acquisition', 'Resume Screening', 'Candidate Sourcing', 'Advanced Excel'],
    category: 'Human Resources',
    categories: ['Human Resources'],
    subCategory: 'Recruiter / Talent Acquisition',
    salaryMin: 400000,
    salaryMax: 700000,
    experienceLevel: 'Fresher',
    experienceMin: 0,
    experienceMax: 2,
    employmentType: 'Full Time',
    workMode: 'On-site',
    locationName: 'B-8, Sector 132, Noida',
    city: 'Noida',
    state: 'Uttar Pradesh',
    location: { type: 'Point', coordinates: [77.3750, 28.5080] }, // Sector 132 (~13 km)
    postedAt: new Date(Date.now() - 20 * 60 * 60 * 1000),
    walkIn: false,
    applyUrl: 'https://www.infoedge.in/careers',
    verified: true,
    status: 'active',
  },

  // 9. Paytm (One97 Communications) - Sector 98, Noida (~10 km)
  {
    _id: '670000000000000000000009',
    title: 'Backend Node.js Engineer',
    companyName: 'Paytm (One97 Communications)',
    companyLogo: 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=100&auto=format&fit=crop&q=80',
    description: 'Build mission-critical payment processing services and high-volume transaction routing engines at Paytm One Skymark campus in Noida using Node.js, Redis, and MongoDB.',
    responsibilities: [
      'Architect resilient backend payment APIs handling millions of daily transactions',
      'Optimize database query speeds and Redis caching strategies',
      'Implement strict security and encryption protocols for financial data',
    ],
    requirements: [
      'Strong experience with Node.js, Express.js, MongoDB, Redis',
      'Understanding of distributed architectures and asynchronous message queues',
      'Passion for scalable fintech systems',
    ],
    skills: ['Node.js', 'Express.js', 'MongoDB', 'Redis', 'JavaScript', 'AWS'],
    category: 'Technology / IT',
    categories: ['Technology / IT'],
    subCategory: 'Backend Development',
    salaryMin: 800000,
    salaryMax: 1600000,
    experienceLevel: '1-3 years',
    experienceMin: 1,
    experienceMax: 3,
    employmentType: 'Full Time',
    workMode: 'Hybrid',
    locationName: 'One Skymark, Sector 98, Noida',
    city: 'Noida',
    state: 'Uttar Pradesh',
    location: { type: 'Point', coordinates: [77.3520, 28.5380] }, // Sector 98 (~10 km)
    postedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    walkIn: false,
    applyUrl: 'https://paytm.com/careers',
    verified: true,
    status: 'active',
  },

  // 10. Adobe Systems India - Sector 132, Noida (~13.5 km)
  {
    _id: '670000000000000000000010',
    title: 'UI/UX & Product Design Specialist',
    companyName: 'Adobe Systems India',
    companyLogo: 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=100&auto=format&fit=crop&q=80',
    description: 'Join Adobe India campus in Noida designing next-generation creative cloud web workflows. Work with global product teams to create intuitive user journeys and scalable design systems.',
    responsibilities: [
      'Design high-fidelity interactive wireframes and design systems in Figma',
      'Conduct user testing and feedback interviews with creative professionals',
      'Collaborate with web engineering squads to maintain design fidelity',
    ],
    requirements: [
      'Impressive portfolio demonstrating digital product design and typography',
      'Mastery of Figma, design systems, and prototyping',
      'Keen eye for aesthetic elegance and accessible UX patterns',
    ],
    skills: ['Figma', 'UI Design', 'UX Research', 'UI/UX Design'],
    category: 'Design',
    categories: ['Design'],
    subCategory: 'UI/UX Design',
    salaryMin: 900000,
    salaryMax: 1900000,
    experienceLevel: '1-3 years',
    experienceMin: 1,
    experienceMax: 3,
    employmentType: 'Full Time',
    workMode: 'Hybrid',
    locationName: 'Adobe Towers, Sector 132, Noida',
    city: 'Noida',
    state: 'Uttar Pradesh',
    location: { type: 'Point', coordinates: [77.3780, 28.5060] }, // Sector 132 (~13.5 km)
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    walkIn: false,
    applyUrl: 'https://www.adobe.com/careers',
    verified: true,
    status: 'active',
  },
];

module.exports = {
  MOCK_JOBS_DATA,
};
